PREFIX 	sibm:  <http://lab.ene.im/SIBM/property#>
PREFIX	rel:   <http://purl.org/vocab/relationship/>

SELECT ?x ?y
WHERE { 
	?x 	rel:childOf		?y .
	?y	rdf:type		<http://lab.ene.im/SIBM/thing/usertype/assistant> .
	?y	sibm:stayAt		<http://lab.ene.im/SIBM/thing/shelterpoint/S1>
}