PREFIX 	sibm:  <http://lab.ene.im/SIBM/property#>
PREFIX 	rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX 	xsd:   <http://www.w3.org/2001/XMLSchema#>

SELECT ?x ?y ?z
WHERE { 
	?x sibm:stayAt	?y .
	?x sibm:studyAt ?z .
	?z a "小学校"^^xsd:string .			
}