PREFIX	geo:   <http://lab.ene.im/SIBM/property/geo#> 
PREFIX 	sibm:  <http://lab.ene.im/SIBM/property#>
PREFIX 	xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX 	rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX 	rel:   <http://purl.org/vocab/relationship/>

SELECT ?x
WHERE { 
	?x rel:parentOf	?y .
	?x sibm:studyAt ?z .
	?z a "小学校"^^xsd:string .			
}