PREFIX 	sibm:  <http://lab.ene.im/SIBM/property#>

SELECT ?Principal ?Child ?Father
WHERE {
	?x		sibm:profile	[sibm:firstName	?_Principal] .
    ?x 		sibm:status		<http://lab.ene.im/SIBM/thing/status/serious> .
    
    OPTIONAL {
		?x	sibm:hasChild 	?y .
		?y	sibm:profile	[sibm:firstName	?_Child]
    }
    
    OPTIONAL {
		?x	sibm:hasFather 	?z .
		?z	sibm:profile	[sibm:firstName	?_Father]
    }
}
