PREFIX	geo:   <http://lab.ene.im/SIBM/property/geo#>
PREFIX 	sibm:  <http://lab.ene.im/SIBM/property#>
PREFIX 	xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX 	rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?gender (count(?p) AS ?count)
WHERE {
    ?p sibm:profile ?y .
    ?y sibm:gender  ?gender ;
} group by ?gender order by ?gender
