PREFIX	sibm:	<http://lab.ene.im/SIBM/property#>
PREFIX	xsd:	<http://www.w3.org/2001/XMLSchema#>

SELECT (count(*) AS ?count)
WHERE {
    ?x sibm:profile ?y .
    ?y sibm:age     ?z ;

    FILTER(?z > "60"^^xsd:integer)
}
